version: '3.7'

services:
  db:
    image: postgres:11-alpine
    container_name: emailsender_db
    environment:
      - POSTGRES_USER=emailsender
      - POSTGRES_DB=emailsender
      - POSTGRES_PASSWORD=password
    ports:
      - 5438:5432
